name: "Add Label to linear"
author: "chowhdaryshivi"

inputs: 
  linear_api_key:
    required: true
    description: "Linear API Key"
  label:
    required: true
    description: "Label to add"
  branch:
    required: true
    description: "Branch name"
  pr_title:
    required: true
    description: "PR title"

runs: 
  using: "docker"
  image: "Dockerfile"
  env:
    LINEAR_API_KEY: ${{ inputs.linear_api_key }}
    LINEAR_LABEL: ${{ inputs.label }}
    BRANCH_NAME: ${{ inputs.branch }}
    PR_TITLE: ${{ inputs.pr_title }}

